name: CI

on: [push, pull_request]

env:
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  SCHEME: ${{ secrets.SCHEME }}

jobs:
  tests:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-

    - name: Xcode Select
      uses: devbotsxyz/xcode-select@v1.1.0
      with:
        version: ${{ secrets.XCODE_VERSION }}

    - name: Carthage Bootstrap
      run: ./carthage.sh bootstrap --cache-builds --no-use-binaries --platform ios

    - name: Run all tests
      run: xcodebuild clean build test -scheme "${SCHEME}" -destination "platform=iOS Simulator,name=iPhone 11" -enableCodeCoverage YES

    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash) -J "${PROJECT_NAME}"

  deploy:
    runs-on: macos-11.0
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-

    - name: Xcode Select
      uses: devbotsxyz/xcode-select@v1.1.0
      with:
        version: ${{ secrets.XCODE_VERSION }}

    - name: Build
      run: ./carthage.sh build --no-skip-current --platform ios
    
    - name: Archive
      run: ./carthage.sh archive ${PROJECT_NAME}
    
    - name: Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        file: ${{ secrets.PROJECT_NAME }}.framework.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
